fix: Enhanced typescript support (#9)
* fix: Add support for generating typescript types using @grpc/proto-loader

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -27,6 +27,14 @@ inputs:
     description: 'Run `buf generate`'
     required: false
     default: 'true'
+  generate-typescript:
+    description: 'Generate typescript types. If true, @grpc/proto-loader will be used to generate grpc stubs and typescript types, and output to dist/nodejs'
+    required: false
+    default: true
+  generate-typescript-protos:
+    description: 'Space delineated string of paths from project root to proto files to generate typescript types for.'
+    required: false
+    default: ""
   breaking:
     description: 'Run `buf breaking`'
     required: false
@@ -86,8 +94,7 @@ runs:
     - name: Install Javascript and Typescript dependencies
       shell: bash
       run: |
-        npm install grpc-tools@1.9.1 --global
-        npm install grpc_tools_node_protoc_ts@5.0.1 --global
+        npm install @grpc/proto-loader --global
     - name: Sign into BSR
       shell: bash
       run: |
@@ -105,6 +112,24 @@ runs:
       shell: bash
       run: |
         node ${{ github.action_path }}/buf.js --workingDirectory='${{ github.workspace }}' --bufCommand='mod update'
+    - name: Verify generate typescript config
+      if: inputs.generate-typescript == 'true' && inputs.generate-typescript-protos == ''
+      shell: bash
+      run: |
+        echo "generate-typescript-protos must be defined to generate typescript stubs"
+        exit 1
+    - name: Generate typescript stubs
+      if: inputs.generate-typescript == 'true'
+      shell: bash
+      # I tried using glob patterns for the protos like ${{ inputs.protos-dir}}/**/*.proto but it fails every time
+      # with errors about not finding the file. It works locally so I'm not sure why it doesn't work here. The chosen
+      # workaround is to require the user to be explicit about which proto files to generate, and process them in a loop
+      run: |
+        files=(${{ inputs.generate-typescript-protos }})
+        for i in "${files[@]}"
+        do
+          proto-loader-gen-types --longs=String --enums=String --defaults --oneofs --grpcLib=@grpc/grpc-js --outDir=dist/nodejs $i
+        done
     - name: Run buf generate
       if: inputs.generate == 'true'
       shell: bash
